title: WORK IN PROGRESS
title_short: WIP
encoding: utf-8
owner: Florent Dufour
email: mayday@dufour.xyz

author: Florent Dufour
description: Clearly a work in progress.
keywords: "AI, bayern, biotechnology, cloud, confidential, cv, digimed, dufour, esbs, florent, health, llm, lrz, medicine, munich, privacy, security, strasbourg, tum, unistra, wip, xyz"
languages: [en, fr]
url: "https://WORKINPROGRESS.dufour.xyz"

timezone: Europe/Paris
theme-color: "#fdf52b" # https://roger.zone/theme-color-preview/

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-feed

# Collections
collections:
  chantiers:
    output: true
    permalink: "/:path.html"
  pages:
    output: true
    permalink: "/:path.html"

# Feed configuration
feed:
  icon: /assets/2025/favicons/dot/dot-32.png
  path: /feeds.xml
  excerpt_only: true
  collections:
    chantiers:
      path: "/feeds/chantiers.xml"
      excerpt_only: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.ko*"
  - .direnv/
  - result
  - result/
  - .idea
  - .DS_Store
  - gitignore.d
  - em_cache