title: WORK IN PROGRESS
title_short: WIP
encoding: utf-8
owner: Florent Dufour
email: info@dufour.xyz

author: Florent Dufour
description: This is the description # TODO
keywords: "florent, dufour, wip, chantiers, projects" # TODO
languages: [en, fr]
url: "https://WORKINPROGRESS.dufour.xyz"


timezone: Europe/Paris

theme-color: "#fdf52b"

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-feed

# Collections
collections:
  chantiers:
    output: true
    permalink: "/:path.html"

# https://github.com/jekyll/jekyll-feed
feed:
  collections:
    chantiers:
      path: "/rss"

# webrick:
#   headers:
#     "Cross-Origin-Opener-Policy": "same-origin"
#     "Cross-Origin-Embedder-Policy": "require-corp"

defaults:
  -
    scope:
      path: "assets/lib"
    values:
      static_file: true
  -
    scope:
      path: "assets/models"
    values:
      static_file: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.ko*"
  - .direnv/
  - result/
  - .idea

include:
  - _headers
  - _redirects
  - assets/lib/
  - assets/models/

# Markdown Processing
# ... existing code ...

