10 PRINT "COMPATIBILITE"\n
20 PRINT "============="\n
30 INPUT "TON PRENOM: ", PRENOM1\n
40 INPUT "SON PRENOM: ", PRENOM2\n
50 SCORE = 0\n
60 IF PRENOM1 = PRENOM2 THEN SCORE = SCORE + 50\n
70 IF LEFT$(PRENOM1,1) = LEFT$(PRENOM2,1) THEN SCORE = SCORE + 5\n
80 IF RIGHT$(PRENOM1,1) = RIGHT$(PRENOM2,1) THEN SCORE = SCORE + 5\n
999 IF SCORE < 100 THEN PRINT "COMPATIBILITE: "; SCORE; "%" ELSE PRINT "COMPATIBILITE: "; 100; "%"\n
1000 INPUT "ENCORE ? (O/N)", REPONSE\n