# Florent Dufour
# 01.2026 MUC

all: npm-install fetch-playlists update-data

npm-install:
	npm install

fetch-playlists:
	node fetch-playlists

update-data:
	mv playlists.json ../../_data/playlists.json