name: Prebuild DJ-DIGGER

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  prebuild-ec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        working-directory: prebuild/DJ-DIGGER/
        run: npm install

      - name: Fetch Apple Music Playlists
        working-directory: prebuild/DJ-DIGGER/
        env:
          APPLE_MUSIC_TOKEN: ${{ secrets.APPLE_MUSIC_TOKEN }}
          MUSIC_USER_TOKEN: ${{ secrets.MUSIC_USER_TOKEN }}
        run: npm run fetch-playlists

      - name: Upload playlists.json as artifact
        uses: actions/upload-artifact@v4
        with:
          name: playlists-json
          path: _data/playlists.json
          retention-days: 90

      - name: Commit and Push changes
        run: |
          git config --global user.name 'automatique [bot]'
          git config --global user.email 'automatique-bot@users.noreply.github.com'
          git add _data/playlists.json
          git diff --staged --quiet || git commit -m "PREBUILD DJ-DIGGER [bot]"
          git push
