name: Prebuild - EC*

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  prebuild-ec*:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Fetch Apple Music Playlists
        env:
          APPLE_MUSIC_TOKEN: ${{ secrets.APPLE_MUSIC_TOKEN }}
          MUSIC_USER_TOKEN: ${{ secrets.MUSIC_USER_TOKEN }}
        run: npm run fetch-playlists

      - name: Commit and Push changes
        run: |
          git config --global user.name 'automatique [bot]'
          git config --global user.email 'automatique [bot]@users.noreply.github.com'
          git add _data/playlists.json
          git commit -m "PREBUILD EC* [bot]"
          git push
